package:
  name: met_test
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.0.1') }}

source:
  path: .

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: 
    - $PYTHON setup.py install


requirements:
  build:
    - python
    - setuptools
    - metpy
    - scipy
    - pygrib
  run:

about:
home: https://github.com/MetServiceDev/met_test.git
